# Generated by Django 3.0.5 on 2020-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
